import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';
import { contentsApi } from '../api/contents';
import { uploadsApi } from '../api/uploads';
import { useAuth } from '../hooks/useAuth';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import { Modal } from '../ui/Modal';
import { CONTENT_TYPE, CONTENT_TYPE_LABELS, DEFAULT_CONTENT_TYPE } from '../constants/enums';

const categories = [
  { value: 'drama', label: 'Drama' }, { value: 'comedia', label: 'Comédia' }, { value: 'acao', label: 'Ação' },
  { value: 'documentario', label: 'Documentário' }, { value: 'teatro-classico', label: 'Teatro Clássico' }, { value: 'stand-up', label: 'Stand-up' },
];
const defaultValues = { title: '', typeContent: DEFAULT_CONTENT_TYPE, description: '', details: '', eventDate: '', eventLocation: '', category: '' };

export default function Publicar() {
  const [posterFile, setPosterFile] = useState(null); const [posterPreview, setPosterPreview] = useState(null); const [videoFile, setVideoFile] = useState(null); const [videoPreview, setVideoPreview] = useState(null); const [uploadProgress, setUploadProgress] = useState(0); const [isConfirmationOpen, setIsConfirmationOpen] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false); const [pendingContent, setPendingContent] = useState(null); const [loadedContent, setLoadedContent] = useState(null); const [submitError, setSubmitError] = useState(''); const [videoError, setVideoError] = useState('');
  const navigate = useNavigate(); const { contentId: paramContentId } = useParams(); const { user } = useAuth();
  const { register, handleSubmit, watch, reset, setError, clearErrors, formState: { errors } } = useForm({ defaultValues });
  const watchCategory = watch('category'); const watchEventDate = watch('eventDate'); const canUploadVideo = Boolean(watchEventDate && new Date(`${watchEventDate}T00:00:00`) <= new Date());

  useEffect(() => () => { if (posterPreview?.startsWith('blob:')) URL.revokeObjectURL(posterPreview); if (videoPreview?.startsWith('blob:')) URL.revokeObjectURL(videoPreview); }, [posterPreview, videoPreview]);
  useEffect(() => { if (paramContentId) loadContent(paramContentId); }, [paramContentId]);
  const handlePosterChange = (event) => { const file = event.target.files?.[0] ?? null; if (posterPreview?.startsWith('blob:')) URL.revokeObjectURL(posterPreview); setPosterFile(file); if (file) { setPosterPreview(URL.createObjectURL(file)); clearErrors('poster'); } else { setPosterPreview(null); if (!loadedContent) setError('poster', { type: 'required', message: 'O cartaz é obrigatório.' }); } };
  const handleVideoChange = (event) => { const file = event.target.files?.[0] ?? null; if (videoPreview?.startsWith('blob:')) URL.revokeObjectURL(videoPreview); if (file && file.type !== 'video/mp4') { setVideoFile(null); setVideoPreview(null); setVideoError('O vídeo deve estar no formato MP4.'); return; } setVideoError(''); setVideoFile(file); setVideoPreview(file ? URL.createObjectURL(file) : null); };
  const loadContent = async (id) => { if (!id) return; try { const response = await contentsApi.getById(id); const content = response.data; setLoadedContent(content); reset({ title: content.title || '', typeContent: content.typeContent || DEFAULT_CONTENT_TYPE, description: content.description || '', details: content.details || '', eventDate: content.eventDate ? content.eventDate.split('T')[0] : '', eventLocation: content.eventLocation || '', category: content.category || '' }); setPosterFile(null); setPosterPreview(content.coverUrl || content.poster?.url || ''); } catch { setSubmitError('Não foi possível carregar o conteúdo.'); } };
  const clearLoadedContent = () => { setLoadedContent(null); setPosterFile(null); setPosterPreview(null); setVideoFile(null); setVideoPreview(null); setSubmitError(''); reset(defaultValues); navigate('/painel/publicar'); };
  const onSubmit = (data) => { if (!posterFile && !loadedContent) { setError('poster', { type: 'required', message: 'O cartaz é obrigatório.' }); return; } if (loadedContent && videoFile && !canUploadVideo) { setVideoError('O vídeo só pode ser enviado na data de exibição ou depois.'); return; } setPendingContent(data); setSubmitError(''); setIsConfirmationOpen(true); };
  const handlePublish = async () => { if (!pendingContent || isSubmitting) return; if (!loadedContent && !user?.id) { setSubmitError('A sua sessão não contém um utilizador válido. Saia da conta e entre novamente.'); return; } setIsSubmitting(true); setUploadProgress(0); setSubmitError(''); try { let coverUrl = loadedContent?.coverUrl || null; if (posterFile) { const imageForm = new FormData(); imageForm.append('file', posterFile); const imageResp = await uploadsApi.uploadImage(imageForm, { onUploadProgress: (evt) => setUploadProgress(Math.round((evt.loaded * 100) / (evt.total || 1) / (videoFile ? 2 : 1))) }); coverUrl = imageResp.data?.url || imageResp.data?.fileUrl || imageResp.data?.path || null; if (!coverUrl) throw new Error('O servidor não devolveu o endereço do cartaz enviado.'); } const contentData = { title: pendingContent.title.trim(), typeContent: pendingContent.typeContent, description: pendingContent.description.trim(), details: pendingContent.details.trim(), category: pendingContent.category, coverUrl, eventDate: pendingContent.eventDate || null, eventLocation: pendingContent.eventLocation.trim() }; if (!contentData.coverUrl) throw new Error('O cartaz é obrigatório.'); let savedContent; if (loadedContent) savedContent = await contentsApi.update(loadedContent.id, contentData); else savedContent = await contentsApi.create({ ...contentData, ownerId: user.id }); if (loadedContent && videoFile) { const videoForm = new FormData(); videoForm.append('file', videoFile); const videoResp = await uploadsApi.uploadVideo(videoForm, { onUploadProgress: (evt) => setUploadProgress(50 + Math.round((evt.loaded * 100) / (evt.total || 1) / 2)) }); await contentsApi.updateVideo(loadedContent.id, videoResp.data?.url, null); } setIsConfirmationOpen(false); setPendingContent(null); navigate('/painel'); } catch (error) { const data = error.response?.data; setSubmitError((typeof data === 'string' && data.trim()) || data?.message || error.message || 'Não foi possível guardar o conteúdo. Verifique os dados e tente novamente.'); } finally { setIsSubmitting(false); setUploadProgress(0); } };
  const handleDelete = async () => { if (!loadedContent) return; setIsSubmitting(true); try { await contentsApi.delete(loadedContent.id); navigate('/painel'); } catch { setSubmitError('Não foi possível excluir o conteúdo.'); } finally { setIsSubmitting(false); } };
  const selectedCategoryLabel = categories.find((item) => item.value === watchCategory)?.label || 'Categoria';

  return <div className="relative min-h-screen overflow-hidden"><div className="pointer-events-none absolute right-0 top-0 h-[600px] w-[40%] opacity-[0.035] afro-pattern text-accent" /><div className="relative mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14">
    <div className="mb-10 border-b border-white/10 pb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[0.25em] text-accent">Arquivo · Publicação</p><h1 className="text-4xl font-black tracking-[-0.04em] sm:text-5xl">{loadedContent ? 'Editar conteúdo' : 'Publicar conteúdo'}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">{loadedContent ? 'Atualize os detalhes da obra e, após a data de exibição, associe o vídeo à obra.' : 'Apresente uma nova obra ao catálogo de cinema e teatro.'}</p></div>
    <div className="grid gap-8 xl:grid-cols-[1.5fr_1fr]">
      <Card className="space-y-6"><CardHeader className="space-y-3"><CardTitle>{loadedContent ? 'Editar conteúdo' : 'Dados da obra'}</CardTitle><p className="text-sm text-muted">Preencha os campos necessários para apresentar a obra.</p></CardHeader><CardContent><form className="space-y-6" onSubmit={handleSubmit(onSubmit)} noValidate>
        <Input label="Título" placeholder="Nome da obra" error={errors.title?.message} {...register('title', { required: 'O título é obrigatório.', minLength: { value: 5, message: 'Use pelo menos 5 caracteres.' } })} />
        <div className="grid gap-4 lg:grid-cols-2"><div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Sinopse</label><textarea className={`min-h-[100px] w-full border px-3 py-2 text-sm text-text transition-colors bg-surface border-white/10 placeholder:text-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${errors.description ? 'border-red-500' : ''}`} placeholder="Uma breve descrição da obra" {...register('description', { required: 'A sinopse é obrigatória.', minLength: { value: 10, message: 'Use pelo menos 10 caracteres.' } })} />{errors.description && <span className="text-xs text-red-500">{errors.description.message}</span>}</div><div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Descrição</label><textarea className={`min-h-[100px] w-full border px-3 py-2 text-sm text-text transition-colors bg-surface border-white/10 placeholder:text-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${errors.details ? 'border-red-500' : ''}`} placeholder="Detalhes completos da obra" {...register('details', { required: 'A descrição é obrigatória.', minLength: { value: 20, message: 'Use pelo menos 20 caracteres.' } })} />{errors.details && <span className="text-xs text-red-500">{errors.details.message}</span>}</div></div>
        <div className="grid gap-4 lg:grid-cols-2"><Input label="Data de exibição" type="date" error={errors.eventDate?.message} {...register('eventDate', { required: 'A data é obrigatória.' })} /><Input label="Local" placeholder="Rua, bairro, cidade" error={errors.eventLocation?.message} {...register('eventLocation', { required: 'O local é obrigatório.', minLength: { value: 5, message: 'Insira um local válido.' } })} /></div>
        <div className="grid gap-4 lg:grid-cols-2"><div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Tipo de conteúdo</label><select className="h-11 border border-white/10 bg-surface px-3 text-sm text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" {...register('typeContent', { required: 'O tipo de conteúdo é obrigatório.' })}>{Object.values(CONTENT_TYPE).map((value) => <option key={value} value={value}>{CONTENT_TYPE_LABELS[value]}</option>)}</select></div><div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Categoria</label><select className="h-11 border border-white/10 bg-surface px-3 text-sm text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" {...register('category', { required: 'A categoria é obrigatória.' })}><option value="">Escolha a categoria</option>{categories.map((category) => <option key={category.value} value={category.value}>{category.label}</option>)}</select>{errors.category && <span className="text-xs text-red-500">{errors.category.message}</span>}</div></div>
        <div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Cartaz</label><input type="file" accept="image/*" onChange={handlePosterChange} className="h-11 border border-white/10 bg-surface px-3 text-sm text-text file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" />{errors.poster && <span className="text-xs text-red-500">{errors.poster.message}</span>}</div>
        {loadedContent && <div className="border border-white/10 bg-surface p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">Vídeo da obra</p><p className="mt-1 text-sm text-muted">{canUploadVideo ? 'A data de exibição chegou. Pode adicionar ou substituir o vídeo.' : `O vídeo só pode ser enviado na data de exibição ou depois.`}</p></div><span className={`text-xs font-semibold ${canUploadVideo ? 'text-emerald-400' : 'text-accent'}`}>{canUploadVideo ? 'Disponível' : 'Bloqueado'}</span></div>{canUploadVideo ? <div className="mt-4 space-y-3"><input type="file" accept="video/mp4" onChange={handleVideoChange} className="h-11 w-full border border-white/10 bg-background px-3 text-sm text-text file:border-0 file:bg-transparent file:text-sm file:font-medium" />{videoError && <p className="text-xs text-red-500">{videoError}</p>}{videoFile && <video controls className="mt-3 max-h-72 w-full bg-black" src={videoPreview} />}{loadedContent.videoUrl && !videoFile && <p className="text-xs text-muted">Já existe um vídeo associado. Selecione outro ficheiro para substituí-lo.</p>}</div> : <p className="mt-4 text-xs text-muted">A obra permanece no catálogo para divulgação até à data de exibição.</p>}</div>}
        <div className="flex flex-wrap gap-3"><Button type="submit" disabled={isSubmitting}>{loadedContent ? 'Guardar alterações' : 'Publicar conteúdo'}</Button>{loadedContent && <Button type="button" variant="secondary" onClick={clearLoadedContent}>Cancelar edição</Button>}{loadedContent && <Button type="button" variant="outline" onClick={handleDelete} disabled={isSubmitting}>Excluir conteúdo</Button>}</div>{submitError && <p className="text-sm text-red-500">{submitError}</p>}
      </form></CardContent></Card>
      <Card><CardHeader><CardTitle>Pré-visualização</CardTitle></CardHeader><CardContent>{posterPreview ? <img src={posterPreview} alt="Pré-visualização do cartaz" className="aspect-[2/3] w-full object-cover" /> : <div className="aspect-[2/3] flex items-center justify-center bg-surface text-muted">Sem cartaz selecionado</div>}<div className="mt-5 space-y-2"><p className="text-xl font-bold">{watch('title') || 'Título da obra'}</p><p className="text-sm text-accent">{selectedCategoryLabel}</p><p className="text-sm leading-6 text-muted">{watch('description') || 'A sinopse da obra aparecerá aqui.'}</p></div></CardContent></Card>
    </div>
  </div>
  <Modal isOpen={isConfirmationOpen} onClose={() => !isSubmitting && setIsConfirmationOpen(false)} title={loadedContent ? 'Confirmar alterações' : 'Confirmar publicação'}><div className="space-y-4"><p className="text-sm text-muted">{loadedContent ? 'Confirme para guardar as alterações desta obra.' : 'Confirme para publicar esta obra no catálogo.'}</p>{isSubmitting && uploadProgress > 0 && <div className="text-sm text-muted">A carregar ficheiros: {uploadProgress}%</div>}{submitError && <p className="text-sm text-red-500">{submitError}</p>}<div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setIsConfirmationOpen(false)} disabled={isSubmitting}>Cancelar</Button><Button onClick={handlePublish} isLoading={isSubmitting}>Confirmar</Button></div></div></Modal>
  </div>;
}
