import { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Upload } from 'lucide-react';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import { Modal } from '../ui/Modal';
import { contentsApi } from '../api/contents';
import { uploadsApi } from '../api/uploads';

function formatDateLabel(value) { if (!value) return 'Data não definida'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Data não definida' : date.toLocaleDateString('pt-PT', { day: '2-digit', month: 'short', year: 'numeric' }); }

export default function PublicarVideo() {
  const [posterFile, setPosterFile] = useState(null); const [videoFile, setVideoFile] = useState(null); const [posterPreview, setPosterPreview] = useState(null); const [videoPreview, setVideoPreview] = useState(null); const [isConfirmationOpen, setIsConfirmationOpen] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false); const [uploadProgress, setUploadProgress] = useState(0); const [pendingData, setPendingData] = useState(null); const [submitError, setSubmitError] = useState(''); const [contentTitle, setContentTitle] = useState('');
  const navigate = useNavigate(); const { contentId: routeContentId } = useParams();
  const { register, handleSubmit, watch, setError, clearErrors, reset, formState: { errors } } = useForm({ defaultValues: { eventDate: '' } });
  const watchEventDate = watch('eventDate'); const isStreamAvailable = useMemo(() => watchEventDate && new Date() >= new Date(watchEventDate), [watchEventDate]);
  useEffect(() => () => { if (posterPreview) URL.revokeObjectURL(posterPreview); if (videoPreview) URL.revokeObjectURL(videoPreview); }, [posterPreview, videoPreview]);
  useEffect(() => { if (!routeContentId) return; contentsApi.getById(routeContentId).then((response) => { setContentTitle(response.data?.title || ''); if (response.data?.eventDate) reset({ eventDate: response.data.eventDate.split('T')[0] }); }).catch(() => setSubmitError('Não foi possível carregar o conteúdo selecionado.')); }, [routeContentId, reset]);
  const handlePosterChange = (event) => { const file = event.target.files?.[0] ?? null; if (posterPreview) URL.revokeObjectURL(posterPreview); if (file && file.type !== 'image/png') { setPosterFile(null); setPosterPreview(null); setError('poster', { type: 'type', message: 'Cartaz precisa ser PNG.' }); return; } clearErrors('poster'); setPosterFile(file); setPosterPreview(file ? URL.createObjectURL(file) : null); };
  const handleVideoChange = (event) => { const file = event.target.files?.[0] ?? null; if (videoPreview) URL.revokeObjectURL(videoPreview); if (file && file.type !== 'video/mp4') { setVideoFile(null); setVideoPreview(null); setError('video', { type: 'type', message: 'O vídeo precisa ser MP4.' }); return; } clearErrors('video'); setVideoFile(file); setVideoPreview(file ? URL.createObjectURL(file) : null); };
  const onSubmit = (data) => { if (!routeContentId) return setSubmitError('Selecione um conteúdo existente para adicionar o vídeo.'); if (!posterFile) return setError('poster', { type: 'required', message: 'Cartaz em PNG obrigatório.' }); if (!videoFile) return setError('video', { type: 'required', message: 'Vídeo em MP4 obrigatório.' }); setPendingData(data); setIsConfirmationOpen(true); };
  const handleUpload = async () => { if (!pendingData || !routeContentId) return; setIsSubmitting(true); setSubmitError(''); try { const imageForm = new FormData(); imageForm.append('file', posterFile); const imageResp = await uploadsApi.uploadImage(imageForm, { onUploadProgress: (event) => setUploadProgress(Math.round((event.loaded * 100) / (event.total || 1) / 2)) }); const videoForm = new FormData(); videoForm.append('file', videoFile); const videoResp = await uploadsApi.uploadVideo(videoForm, { onUploadProgress: (event) => setUploadProgress(50 + Math.round((event.loaded * 100) / (event.total || 1) / 2)) }); await contentsApi.updateVideo(routeContentId, videoResp.data?.url, imageResp.data?.url); setIsConfirmationOpen(false); navigate('/painel'); } catch (error) { const data = error.response?.data; setSubmitError((typeof data === 'string' && data.trim()) || data?.message || 'Não foi possível concluir o upload. Tente novamente.'); } finally { setIsSubmitting(false); setUploadProgress(0); } };

  return <div className="relative min-h-screen overflow-hidden"><div className="pointer-events-none absolute right-0 top-0 h-[600px] w-[40%] opacity-[0.035] afro-pattern text-accent" /><div className="relative mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14">
    <div className="mb-10 flex flex-col gap-5 border-b border-white/10 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.25em] text-accent">Arquivo · Exibição</p><h1 className="text-4xl font-black tracking-[-0.04em] sm:text-5xl">Adicionar vídeo</h1><p className="mt-3 text-sm text-muted">Associe a exibição audiovisual a uma obra já publicada.</p></div><Link to="/painel" className="inline-flex items-center gap-2 border border-white/10 bg-surface px-4 py-2 text-sm font-semibold text-text transition hover:border-accent/40 hover:text-accent"><ArrowLeft size={16} /> Voltar</Link></div>
    <div className="grid gap-8 xl:grid-cols-[1.4fr_1fr]">
      <Card><CardHeader><CardTitle>Ficheiros da exibição</CardTitle><p className="text-sm text-muted">{contentTitle ? `Obra: ${contentTitle}` : 'Selecione os ficheiros da obra.'}</p></CardHeader><CardContent>{submitError && !isConfirmationOpen && <div className="mb-5 border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">{submitError}</div>}<form className="space-y-6" onSubmit={handleSubmit(onSubmit)} noValidate>
        <Input label="Data de exibição" type="date" error={errors.eventDate?.message} {...register('eventDate', { required: 'A data de exibição é obrigatória.' })} />
        <div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Cartaz PNG</label><input type="file" accept="image/png" onChange={handlePosterChange} className="h-11 border border-white/10 bg-surface px-3 text-sm text-text file:border-0 file:bg-transparent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" />{errors.poster && <span className="text-xs text-red-500">{errors.poster.message}</span>}</div>
        <div className="flex flex-col gap-1.5"><label className="text-sm font-medium">Vídeo MP4</label><input type="file" accept="video/mp4" onChange={handleVideoChange} className="h-11 border border-white/10 bg-surface px-3 text-sm text-text file:border-0 file:bg-transparent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" />{errors.video && <span className="text-xs text-red-500">{errors.video.message}</span>}</div>
        <Button type="submit" className="w-full" isLoading={isSubmitting}>Enviar ficheiros</Button>
      </form></CardContent></Card>
      <Card><CardHeader><CardTitle>Pré-visualização</CardTitle><p className="text-sm text-muted">Pré-visualize a obra antes da confirmação.</p></CardHeader><CardContent className="space-y-4"><div className="border border-white/10 bg-background p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.18em] text-muted">Data de exibição</p><p className="mt-1 font-semibold">{formatDateLabel(watchEventDate)}</p></div><span className={`px-3 py-1 text-xs font-semibold ${isStreamAvailable ? 'bg-emerald-500/15 text-emerald-400' : 'bg-accent/10 text-accent'}`}>{isStreamAvailable ? 'Disponível' : 'Após a data'}</span></div></div><div className="border border-white/10 bg-surface p-4"><p className="text-xs uppercase tracking-[0.18em] text-muted">Cartaz</p>{posterPreview ? <img src={posterPreview} alt="Cartaz preview" className="mt-3 aspect-video w-full object-cover" /> : <div className="mt-3 flex h-48 items-center justify-center border border-dashed border-white/10 text-sm text-muted">Ainda não selecionado</div>}</div><div className="border border-white/10 bg-surface p-4"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-muted">Vídeo</p><p className="mt-1 text-sm">{videoFile?.name ?? 'Nenhum ficheiro selecionado'}</p></div><Upload size={18} className="text-accent" /></div>{videoPreview && <div className="mt-3">{isStreamAvailable ? <video controls className="w-full bg-black" src={videoPreview} /> : <div className="flex h-32 items-center justify-center border border-dashed border-white/10 text-center text-sm text-muted">A exibição ficará disponível após {formatDateLabel(watchEventDate)}.</div>}</div>}</div>{uploadProgress > 0 && <div className="space-y-2"><div className="flex justify-between text-xs text-muted"><span>A enviar</span><span>{uploadProgress}%</span></div><div className="h-1.5 overflow-hidden bg-white/10"><div className="h-full bg-accent transition-all" style={{ width: `${uploadProgress}%` }} /></div></div>}</CardContent></Card>
    </div>
    <Modal isOpen={isConfirmationOpen} onClose={() => !isSubmitting && setIsConfirmationOpen(false)} title="Confirmar envio"><div className="space-y-5"><p className="text-sm leading-6 text-muted">Confirme o envio dos ficheiros para a obra selecionada.</p><div className="border border-white/10 bg-surface p-4"><p className="text-xs uppercase tracking-[0.2em] text-muted">Obra</p><p className="mt-1 font-semibold">{contentTitle || 'Conteúdo selecionado'}</p></div><div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setIsConfirmationOpen(false)} disabled={isSubmitting}>Cancelar</Button><Button onClick={handleUpload} isLoading={isSubmitting}>Confirmar envio</Button></div></div></Modal>
  </div></div>;
}
