import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '../ui/Card';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { useAuth } from '../hooks/useAuth';

export default function RegisterStudio() {
  const [isSubmitting, setIsSubmitting] = useState(false); const { registerStudio } = useAuth(); const navigate = useNavigate(); const { register, handleSubmit, formState: { errors } } = useForm({ defaultValues: { name: '', nif: '', phone: '', email: '', password: '' } });
  const onSubmit = async (data) => { setIsSubmitting(true); try { await registerStudio(data); navigate('/painel'); } catch (error) { console.error('Erro ao registar estúdio.', error); } finally { setIsSubmitting(false); } };
  return <div className="relative flex flex-1 items-center justify-center overflow-hidden px-5 py-12 sm:px-8"><div className="pointer-events-none absolute left-0 top-0 h-full w-1/2 opacity-[0.035] afro-grid text-accent" /><div className="relative w-full max-w-lg"><div className="mb-8 text-center"><p className="mb-3 text-xs font-bold uppercase tracking-[0.25em] text-accent">Cine Teatro · Criadores</p><h1 className="text-3xl font-black tracking-tight">Registo de produtor ou estúdio</h1><p className="mt-3 text-sm text-muted">Apresente as suas produções no catálogo de cinema e teatro.</p></div><Card><CardHeader><CardTitle>Dados profissionais</CardTitle></CardHeader><CardContent><form className="space-y-5" onSubmit={handleSubmit(onSubmit)}><Input label="Nome da empresa/estúdio" placeholder="Angola Produções" error={errors.name?.message} {...register('name', { required: 'O nome é obrigatório' })} /><div className="grid gap-4 sm:grid-cols-2"><Input label="NIF" placeholder="000000000" error={errors.nif?.message} {...register('nif', { required: 'NIF é obrigatório', minLength: { value: 9, message: 'NIF inválido' } })} /><Input label="Telefone" placeholder="+244 9XX XXX XXX" error={errors.phone?.message} {...register('phone', { required: 'Telefone é obrigatório' })} /></div><Input label="Email profissional" type="email" placeholder="contacto@estudio.co.ao" error={errors.email?.message} {...register('email', { required: 'O email é obrigatório', pattern: { value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i, message: 'Endereço de email inválido' } })} /><Input label="Palavra-passe" type="password" placeholder="••••••••" error={errors.password?.message} {...register('password', { required: 'A palavra-passe é obrigatória', minLength: { value: 6, message: 'Mínimo 6 caracteres' } })} /><Button type="submit" className="w-full" isLoading={isSubmitting}>Solicitar registo</Button></form></CardContent><CardFooter className="justify-center border-t border-white/10"><p className="text-sm text-muted">Já tem uma conta? <Link to="/entrar" className="font-semibold text-accent hover:underline">Entrar</Link></p></CardFooter></Card></div></div>;
}
