import { useState, useEffect, useCallback, useRef } from 'react';
import { adminApi } from '../../api/admin';
import { Button } from '../../ui/Button';
import { Card, CardContent } from '../../ui/Card';
import { Modal } from '../../ui/Modal';
import { EmptyState } from '../../ui/EmptyState';
import { ShieldCheck } from 'lucide-react';
import { CONTENT_STATUS } from '../../constants/enums';

const POLL_INTERVAL_MS = 5000;
export default function AdminDashboard() {
  const [stats, setStats] = useState(null); const [users, setUsers] = useState([]); const [pending, setPending] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [rejectingId, setRejectingId] = useState(null); const [rejectReason, setRejectReason] = useState(''); const [actioningId, setActioningId] = useState(null); const [actionError, setActionError] = useState(''); const [deletingUserId, setDeletingUserId] = useState(null); const pollRef = useRef(null);
  const extractErrorMessage = (err, fallback) => { const data = err.response?.data; if (typeof data === 'string' && data.trim()) return data; if (data?.message) return data.message; return fallback; };
  const loadAll = useCallback(async (showSpinner = false) => { if (showSpinner) setLoading(true); try { const [statsRes, usersRes, pendingRes] = await Promise.all([adminApi.getStats(), adminApi.getUsers(), adminApi.getContents(CONTENT_STATUS.PENDING)]); setStats(statsRes.data); setUsers(usersRes.data); setPending(pendingRes.data); setError(''); } catch (err) { setError(err.response?.status === 403 ? 'Acesso restrito ao administrador.' : 'Não foi possível carregar os dados.'); } finally { setLoading(false); } }, []);
  useEffect(() => { loadAll(true); pollRef.current = setInterval(() => loadAll(false), POLL_INTERVAL_MS); return () => clearInterval(pollRef.current); }, [loadAll]);
  const handleApprove = async (id) => { setActioningId(id); setActionError(''); try { await adminApi.approve(id); await loadAll(false); } catch (err) { setActionError(extractErrorMessage(err, 'Não foi possível aprovar a publicação.')); } finally { setActioningId(null); } };
  const openReject = (id) => { setRejectingId(id); setRejectReason(''); setActionError(''); };
  const confirmReject = async () => { if (!rejectReason.trim()) return; setActioningId(rejectingId); try { await adminApi.reject(rejectingId, rejectReason.trim()); setRejectingId(null); await loadAll(false); } catch (err) { setActionError(extractErrorMessage(err, 'Não foi possível rejeitar a publicação.')); } finally { setActioningId(null); } };
  const handleDeleteUser = async (user) => { if (!confirm(`Eliminar o utilizador "${user.name}"? Esta ação não pode ser desfeita.`)) return; setDeletingUserId(user.id); setActionError(''); try { await adminApi.deleteUser(user.id); await loadAll(false); } catch (err) { setActionError(extractErrorMessage(err, 'Não foi possível eliminar o utilizador.')); } finally { setDeletingUserId(null); } };
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center text-sm text-muted">A carregar painel de administração...</div>;
  if (error) return <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-12"><EmptyState icon={ShieldCheck} title="Não foi possível aceder" description={error} /></div>;
  return <div className="relative min-h-screen overflow-hidden"><div className="pointer-events-none absolute right-0 top-0 h-[600px] w-[40%] opacity-[0.035] afro-pattern text-accent" /><main className="relative mx-auto max-w-7xl space-y-10 px-5 py-10 sm:px-8 lg:px-12 lg:py-14"><header className="border-b border-white/10 pb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[0.25em] text-accent">Controlo da plataforma</p><h1 className="text-4xl font-black tracking-[-0.04em] sm:text-5xl">Painel do Administrador</h1><p className="mt-3 text-sm text-muted">Utilizadores, publicações e validação de conteúdos.</p></header>{actionError && <div className="border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">{actionError}</div>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Total de inscritos', stats?.totalUsers ?? 0, 'text-white'], ['Total de publicações', stats?.totalPublications ?? 0, 'text-white'], ['Pendentes', pending.length, 'text-accent'], ['Aprovadas', stats?.publicationsByStatus?.APPROVED ?? 0, 'text-green-400']].map(([label, value, color]) => <Card key={label}><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.2em] text-muted">{label}</p><p className={`mt-2 text-3xl font-black ${color}`}>{value}</p></CardContent></Card>)}</div>
    <section><div className="mb-5 flex items-center gap-3"><span className="h-px w-8 bg-accent" /><h2 className="text-2xl font-black">Publicações pendentes de validação</h2></div>{pending.length === 0 ? <EmptyState icon={ShieldCheck} title="Nada pendente" description="Não há publicações à espera de validação neste momento." /> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{pending.map((content) => <Card key={content.id}><CardContent className="space-y-4 p-4"><div className="aspect-video overflow-hidden bg-background"><img src={content.coverUrl} alt={content.title} className="h-full w-full object-cover" /></div><div><h3 className="font-bold">{content.title}</h3><p className="mt-1 text-xs text-muted">Por {content.ownerName || 'Desconhecido'} · {content.eventDate}</p></div><div className="flex gap-2"><Button size="sm" onClick={() => handleApprove(content.id)} isLoading={actioningId === content.id}>Aprovar</Button><Button size="sm" variant="outline" onClick={() => openReject(content.id)} disabled={actioningId === content.id}>Rejeitar</Button></div></CardContent></Card>)}</div>}</section>
    <section><div className="mb-5 flex items-center gap-3"><span className="h-px w-8 bg-accent" /><h2 className="text-2xl font-black">Utilizadores inscritos ({users.length})</h2></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b border-white/10 text-left text-muted"><th className="p-4">Nome</th><th className="p-4">Email</th><th className="p-4">Papel</th><th className="p-4" /></tr></thead><tbody>{users.map((u) => <tr key={u.id} className="border-b border-white/5 last:border-0"><td className="p-4 font-semibold">{u.name}</td><td className="p-4 text-muted">{u.email}</td><td className="p-4 text-accent">{u.role}</td><td className="p-4 text-right">{u.role !== 'ADMIN' && <Button size="sm" variant="outline" onClick={() => handleDeleteUser(u)} isLoading={deletingUserId === u.id}>Eliminar</Button>}</td></tr>)}</tbody></table></CardContent></Card></section>
    {stats?.publicationsByStudio?.length > 0 && <section><div className="mb-5 flex items-center gap-3"><span className="h-px w-8 bg-accent" /><h2 className="text-2xl font-black">Publicações por estúdio/grupo</h2></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b border-white/10 text-left text-muted"><th className="p-4">Estúdio/Grupo</th><th className="p-4">Publicações</th></tr></thead><tbody>{stats.publicationsByStudio.map((s) => <tr key={s.ownerId} className="border-b border-white/5 last:border-0"><td className="p-4">{s.ownerName}</td><td className="p-4">{s.total}</td></tr>)}</tbody></table></CardContent></Card></section>}
    <Modal isOpen={rejectingId !== null} onClose={() => setRejectingId(null)} title="Motivo da rejeição"><div className="space-y-4"><p className="text-sm text-muted">Explique ao estúdio/grupo porque a publicação está a ser rejeitada.</p><textarea className="min-h-[100px] w-full border border-white/10 bg-surface px-3 py-2 text-sm text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" placeholder="Ex.: o vídeo não corresponde à sinopse enviada." value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} /><div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setRejectingId(null)}>Cancelar</Button><Button onClick={confirmReject} isLoading={actioningId === rejectingId} disabled={!rejectReason.trim()}>Confirmar rejeição</Button></div></div></Modal>
  </main></div>;
}
